feature - actuator and adjusting migrations system for local debug

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -1,12 +1,10 @@
 name: Build and Deploy to EC2
-
 on:
   push:
     branches:
       - master
-
 jobs:
-  build:
+  run-tests:
     runs-on: ubuntu-latest
     steps:
       - name: 🔄 Checkout code
@@ -18,12 +16,12 @@ jobs:
           distribution: 'temurin'
           java-version: '21'
 
-      - name: 📦 Package JAR
-        run: ./mvnw clean package -DskipTests
+      - name: ✅ Run Tests
+        run: ./mvnw test
 
   push-image:
     runs-on: ubuntu-latest
-    needs: build
+    needs: run-tests
     steps:
       - name: 🔄 Checkout code
         uses: actions/checkout@v3
@@ -51,5 +49,19 @@ jobs:
           key: ${{ secrets.SSH_KEY }}
           script: |
             cd /opt/reduceme
-            docker-compose -f docker-compose-prd.yaml pull
-            docker-compose -f docker-compose-prd.yaml up -d
+            docker compose -f docker-compose-prd.yaml pull
+            docker compose -f docker-compose-prd.yaml up -d
+  health-check:
+      runs-on: ubuntu-latest
+      needs: deploy
+      steps:
+        - name: 🏥 Check health
+        - run:
+            |
+            URL="https://52.14.22.60:8080/actuator/health"
+            STATUS=$(curl -s -o /dev/null -w "%{http_code}" $URL)
+            if [ "$STATUS" -ne 200 ]; then
+              echo "❌ Health check failed for $URL"
+              exit 1
+            fi
+            echo "✅ $URL is healthy"
